"""
SMC Strategy Backtester for LumiTrade.

Uses vectorbt to backtest signals generated by the SMCAnalyzer against
historical OHLCV data. Currently uses sample data as a placeholder until
broker data connectors are integrated.
"""

import asyncio
import logging
from datetime import datetime, timezone

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


def _generate_sample_ohlcv(
    symbol: str, periods: int = 500, freq: str = "h"
) -> pd.DataFrame:
    """Generate synthetic OHLCV data for backtesting development.

    Will be replaced by historical broker data once connectors are ready.
    """
    rng = np.random.default_rng(hash(symbol) & 0xFFFFFFFF)
    base = 100.0
    prices = [base]
    for _ in range(periods - 1):
        prices.append(prices[-1] * (1 + rng.normal(0.0002, 0.012)))

    closes = np.array(prices)
    highs = closes * (1 + rng.uniform(0.001, 0.01, periods))
    lows = closes * (1 - rng.uniform(0.001, 0.01, periods))
    opens = lows + rng.uniform(0, 1, periods) * (highs - lows)
    volumes = rng.integers(1000, 50000, periods).astype(float)

    idx = pd.date_range(end=datetime.now(tz=timezone.utc), periods=periods, freq=freq)

    return pd.DataFrame(
        {"open": opens, "high": highs, "low": lows, "close": closes, "volume": volumes},
        index=idx,
    )


async def run_smc_backtest(
    symbol: str,
    timeframe: str = "1h",
    start_date: str | None = None,
    end_date: str | None = None,
    initial_capital: float = 10_000.0,
) -> dict:
    """Run an SMC-based backtest on historical data.

    Parameters
    ----------
    symbol : str
        Instrument symbol (e.g. "EURUSD").
    timeframe : str
        Candle timeframe (e.g. "15m", "1h", "4h").
    start_date : str | None
        ISO date string for backtest start (placeholder, not yet filtered).
    end_date : str | None
        ISO date string for backtest end (placeholder, not yet filtered).
    initial_capital : float
        Starting capital in USD.

    Returns
    -------
    dict
        {
            "symbol": str,
            "timeframe": str,
            "total_return": float,       # percentage
            "sharpe_ratio": float,
            "max_drawdown": float,       # percentage (negative)
            "win_rate": float,           # 0-1
            "profit_factor": float,
            "total_trades": int,
            "report_summary": str,
            "ran_at": str                # ISO timestamp
        }
    """
    try:
        import vectorbt as vbt
    except ImportError:
        return {
            "error": "vectorbt is not installed. Install with: pip install vectorbt",
            "symbol": symbol,
            "timeframe": timeframe,
        }

    try:
        from .smc_strategy import SMCAnalyzer
    except ImportError:
        from smc_strategy import SMCAnalyzer

    # -- Generate sample data (placeholder) --
    freq_map = {"1m": "min", "5m": "5min", "15m": "15min", "30m": "30min",
                "1h": "h", "4h": "4h", "1d": "D"}
    freq = freq_map.get(timeframe, "h")
    ohlc = await asyncio.to_thread(_generate_sample_ohlcv, symbol, 500, freq)

    # -- Run SMC analysis to get signals --
    try:
        analyzer = SMCAnalyzer()
        analysis = analyzer._analyze_timeframe(ohlc, timeframe)
    except Exception as exc:
        return {
            "error": f"SMC analysis failed: {exc}",
            "symbol": symbol,
            "timeframe": timeframe,
        }

    entry_zones = analysis.get("entry_zones", [])

    # -- Build entry/exit boolean arrays from signals --
    n = len(ohlc)
    entries = np.zeros(n, dtype=bool)
    exits = np.zeros(n, dtype=bool)

    close_prices = ohlc["close"].values

    for zone in entry_zones:
        entry_price = zone["entry"]
        sl = zone["stop_loss"]
        direction = zone["direction"]

        # Find candles near the entry price (within 0.5%)
        for i in range(1, n - 1):
            price = close_prices[i]
            if abs(price - entry_price) / entry_price < 0.005:
                if direction == "long":
                    entries[i] = True
                    # Exit at 2:1 RR or stop loss
                    risk = abs(entry_price - sl)
                    tp = entry_price + risk * 2
                    for j in range(i + 1, n):
                        if close_prices[j] >= tp or close_prices[j] <= sl:
                            exits[j] = True
                            break
                    else:
                        # Exit at last candle if no TP/SL hit
                        exits[n - 1] = True
                    break
                else:
                    # Short: for vectorbt basic mode we still mark entry
                    entries[i] = True
                    risk = abs(sl - entry_price)
                    tp = entry_price - risk * 2
                    for j in range(i + 1, n):
                        if close_prices[j] <= tp or close_prices[j] >= sl:
                            exits[j] = True
                            break
                    else:
                        exits[n - 1] = True
                    break

    # Ensure at least one entry for vectorbt not to error
    if not entries.any():
        return {
            "symbol": symbol,
            "timeframe": timeframe,
            "total_return": 0.0,
            "sharpe_ratio": 0.0,
            "max_drawdown": 0.0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "total_trades": 0,
            "report_summary": "No entry signals generated from sample data.",
            "ran_at": datetime.now(tz=timezone.utc).isoformat(),
        }

    # -- Run vectorbt portfolio simulation --
    try:
        pf = vbt.Portfolio.from_signals(
            close=ohlc["close"],
            entries=pd.Series(entries, index=ohlc.index),
            exits=pd.Series(exits, index=ohlc.index),
            init_cash=initial_capital,
            fees=0.001,       # 0.1% commission
            slippage=0.001,   # 0.1% slippage
            freq=timeframe,
        )

        stats = pf.stats()
        total_return = float(stats.get("Total Return [%]", 0))
        sharpe = float(stats.get("Sharpe Ratio", 0))
        max_dd = float(stats.get("Max Drawdown [%]", 0))
        win_rate = float(stats.get("Win Rate [%]", 0)) / 100.0
        total_trades = int(stats.get("Total Trades", 0))

        # Profit factor: sum of winning trades / abs(sum of losing trades)
        try:
            trades = pf.trades.records_readable
            wins = trades[trades["PnL"] > 0]["PnL"].sum()
            losses = abs(trades[trades["PnL"] < 0]["PnL"].sum())
            profit_factor = float(wins / losses) if losses > 0 else float("inf")
        except Exception:
            profit_factor = 0.0

        report = (
            f"SMC Backtest: {symbol} ({timeframe}) | "
            f"Return: {total_return:.2f}% | Sharpe: {sharpe:.2f} | "
            f"MaxDD: {max_dd:.2f}% | WinRate: {win_rate:.1%} | "
            f"PF: {profit_factor:.2f} | Trades: {total_trades}"
        )

        return {
            "symbol": symbol,
            "timeframe": timeframe,
            "total_return": round(total_return, 4),
            "sharpe_ratio": round(sharpe, 4),
            "max_drawdown": round(-abs(max_dd), 4),
            "win_rate": round(win_rate, 4),
            "profit_factor": round(profit_factor, 4),
            "total_trades": total_trades,
            "report_summary": report,
            "ran_at": datetime.now(tz=timezone.utc).isoformat(),
        }

    except Exception as exc:
        return {
            "error": f"vectorbt backtest failed: {exc}",
            "symbol": symbol,
            "timeframe": timeframe,
        }
